version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: anclora-n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=anclora2025
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=Europe/Madrid
      - N8N_METRICS=true
      - N8N_LOG_LEVEL=info
    volumes:
      - n8n_data:/home/node/.n8n
      - ./workflows:/home/node/.n8n/workflows
      - ./credentials:/home/node/.n8n/credentials
    networks:
      - anclora-network

  # Redis para N8N (opcional, para mejor performance)
  redis:
    image: redis:7-alpine
    container_name: anclora-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - anclora-network

volumes:
  n8n_data:
  redis_data:

networks:
  anclora-network:
    external: true