services:
  backend:
    build: ../backend
    ports:
      - "5000:5000"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ../backend:/app
    depends_on:
      - db

  frontend:
    build: ../frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_SUPABASE_URL=${SUPABASE_URL}
      - REACT_APP_SUPABASE_KEY=${SUPABASE_KEY}
    volumes:
      - ../frontend:/app
      - /app/node_modules

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: anclora_cortex
      POSTGRES_USER: anclora
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:  
